import type { ResourceDefinition, ResourceKey } from "@/types/admin";

const resources: Record<ResourceKey, ResourceDefinition> = {
  members: {
    key: "members",
    title: "会员管理",
    eyebrow: "CRM",
    description: "跨租户查看平台会员档案；列表来自超级管理员只读接口。",
    permission: "member.read",
    scope: "site",
    primaryOperation: "listAdminMembers",
    operations: ["listAdminMembers"],
    columns: [
      { key: "name", label: "会员", minWidth: 150 },
      { key: "mobile", label: "手机号", minWidth: 140 },
      { key: "owner", label: "所属租户", minWidth: 140 },
      { key: "cards", label: "所属场馆", minWidth: 140 },
      { key: "lastVisit", label: "加入时间", type: "date", minWidth: 130 },
      { key: "status", label: "状态", type: "status", width: 100 },
    ],
    actions: [
      { key: "view", label: "查看", permission: "member.read" },
      { key: "edit", label: "编辑", permission: "member.update" },
    ],
  },
  courses: {
    key: "courses",
    title: "课程目录",
    eyebrow: "CATALOG",
    description: "跨租户查看团课、私教课程及其展示状态；业务修改仍由员工端课程服务完成。",
    permission: "course-catalog.read",
    scope: "site",
    primaryOperation: "listAdminResourceData",
    operations: ["listAdminResourceData"],
    columns: [
      { key: "name", label: "课程", minWidth: 180 },
      { key: "type", label: "类型", width: 100 },
      { key: "duration", label: "时长", width: 100 },
      { key: "coaches", label: "适用教练", width: 110 },
      { key: "updatedAt", label: "最近更新", type: "date", minWidth: 150 },
      { key: "status", label: "状态", type: "status", width: 100 },
    ],
    actions: [{ key: "view", label: "查看" }, { key: "edit", label: "编辑", permission: "course-catalog.update" }],
  },
  schedules: {
    key: "schedules",
    title: "排课管理",
    eyebrow: "SCHEDULING",
    description: "按日历查看课程场次、容量和教练安排。调课与停课由后端进行冲突校验。",
    permission: "schedule.read",
    scope: "site",
    primaryOperation: "listAdminResourceData",
    operations: ["listAdminResourceData"],
    columns: [
      { key: "time", label: "开始时间", type: "date", minWidth: 170 },
      { key: "course", label: "课程", minWidth: 160 },
      { key: "coach", label: "教练", width: 110 },
      { key: "room", label: "教室", width: 110 },
      { key: "capacity", label: "预约/容量", width: 110 },
      { key: "status", label: "状态", type: "status", width: 100 },
    ],
    actions: [{ key: "view", label: "详情" }, { key: "adjust", label: "调课", permission: "schedule.update" }],
  },
  appointments: {
    key: "appointments",
    title: "预约与履约",
    eyebrow: "BOOKING",
    description: "查看预约、候补、签到和旷课状态，席位结果以服务端事务结果为准。",
    permission: "booking.read",
    scope: "site",
    primaryOperation: "listAdminResourceData",
    operations: ["listAdminResourceData"],
    columns: [
      { key: "member", label: "会员", minWidth: 140 },
      { key: "session", label: "场次", minWidth: 180 },
      { key: "bookedAt", label: "预约时间", type: "date", minWidth: 170 },
      { key: "card", label: "使用权益", minWidth: 160 },
      { key: "status", label: "履约状态", type: "status", width: 110 },
    ],
    actions: [{ key: "view", label: "查看" }, { key: "checkin", label: "签到", permission: "booking.check-in" }],
  },
  cards: {
    key: "cards",
    title: "会员卡与权益",
    eyebrow: "ENTITLEMENT",
    description: "持卡余额用于快速展示，真实权益以不可变流水为准。",
    permission: "member-card.read",
    scope: "site",
    primaryOperation: "listAdminResourceData",
    operations: ["listAdminResourceData"],
    columns: [
      { key: "member", label: "会员", minWidth: 130 },
      { key: "product", label: "卡产品", minWidth: 180 },
      { key: "balance", label: "剩余权益", minWidth: 130 },
      { key: "expires", label: "有效期至", type: "date", minWidth: 130 },
      { key: "status", label: "状态", type: "status", width: 100 },
    ],
    actions: [{ key: "ledger", label: "流水" }, { key: "adjust", label: "调整", permission: "member-card.adjust" }],
  },
  orders: {
    key: "orders",
    title: "订单管理",
    eyebrow: "COMMERCE",
    description: "订单金额、补正与退款均由服务端规则计算，后台只提交业务意图。",
    permission: "order.read",
    scope: "site",
    primaryOperation: "listAdminResourceData",
    operations: ["listAdminResourceData"],
    columns: [
      { key: "orderNo", label: "订单号", minWidth: 180 },
      { key: "member", label: "会员", minWidth: 130 },
      { key: "item", label: "商品", minWidth: 180 },
      { key: "amount", label: "实付金额", type: "money", width: 120 },
      { key: "createdAt", label: "创建时间", type: "date", minWidth: 170 },
      { key: "status", label: "状态", type: "status", width: 100 },
    ],
    actions: [{ key: "view", label: "详情" }, { key: "correct", label: "补正", permission: "order.correct" }],
  },
  sites: {
    key: "sites",
    title: "租户与场馆",
    eyebrow: "ORGANIZATION",
    description: "跨租户查看平台客户、场馆、会员和员工规模。",
    permission: "site.read",
    scope: "tenant",
    primaryOperation: "listAdminTenants",
    operations: ["listAdminTenants"],
    columns: [
      { key: "name", label: "租户", minWidth: 180 },
      { key: "manager", label: "租户编码", width: 120 },
      { key: "members", label: "会员数", type: "number", width: 100 },
      { key: "todayClasses", label: "场馆数", type: "number", width: 100 },
      { key: "address", label: "员工规模", minWidth: 140 },
      { key: "status", label: "状态", type: "status", width: 100 },
    ],
    actions: [{ key: "view", label: "查看" }, { key: "edit", label: "配置", permission: "site.update" }],
  },
  staff: {
    key: "staff",
    title: "员工与权限",
    eyebrow: "ACCESS",
    description: "管理员工身份、任职场馆和角色；实际授权始终由服务端校验。",
    permission: "staff.read",
    scope: "tenant",
    primaryOperation: "listAdminResourceData",
    operations: ["listAdminResourceData"],
    columns: [
      { key: "name", label: "员工", minWidth: 140 },
      { key: "employeeNo", label: "工号", width: 110 },
      { key: "role", label: "角色", minWidth: 130 },
      { key: "site", label: "主要场馆", minWidth: 150 },
      { key: "lastActive", label: "最近活跃", minWidth: 130 },
      { key: "status", label: "状态", type: "status", width: 100 },
    ],
    actions: [{ key: "view", label: "查看" }, { key: "role", label: "权限", permission: "staff.role.update" }],
  },
  reports: {
    key: "reports",
    title: "经营报表",
    eyebrow: "REPORTING",
    description: "平台级指标由服务端事实表汇总生成，不在浏览器内计算金额或业务结果。",
    permission: "report.read",
    scope: "site",
    primaryOperation: "getAdminDashboard",
    operations: ["getAdminDashboard"],
    columns: [
      { key: "metric", label: "指标", minWidth: 180 },
      { key: "today", label: "当前值", minWidth: 120 },
      { key: "month", label: "统计范围", minWidth: 120 },
      { key: "trend", label: "更新方式", minWidth: 110 },
      { key: "source", label: "事实来源", minWidth: 180 },
      { key: "status", label: "数据状态", type: "status", width: 110 },
    ],
    actions: [{ key: "drill", label: "下钻" }, { key: "export", label: "导出", permission: "report.export" }],
  },
  audit: {
    key: "audit",
    title: "操作审计",
    eyebrow: "AUDIT",
    description: "追踪敏感写操作的操作者、对象、请求编号与结果。审计记录只读。",
    permission: "audit.read",
    scope: "tenant",
    primaryOperation: "listAdminAuditLogs",
    operations: ["listAdminAuditLogs"],
    columns: [
      { key: "time", label: "时间", minWidth: 150 },
      { key: "actor", label: "操作者", width: 120 },
      { key: "action", label: "操作", minWidth: 160 },
      { key: "subject", label: "对象", minWidth: 180 },
      { key: "requestId", label: "请求编号", minWidth: 190 },
      { key: "status", label: "结果", type: "status", width: 90 },
    ],
    actions: [{ key: "view", label: "详情" }],
  },
};

export function getResource(key: string) {
  return resources[key as ResourceKey];
}

export const resourceRegistry = resources;
