<?php

use App\Http\Middleware\AssignRequestId;
use App\Http\Middleware\EnsureDevToolsAccess;
use App\Http\Middleware\EnsureMemberContext;
use App\Http\Middleware\EnsureStaffContext;
use App\Support\ApiResponse;
use Illuminate\Auth\AuthenticationException;
use Illuminate\Database\Eloquent\ModelNotFoundException;
use Illuminate\Foundation\Application;
use Illuminate\Foundation\Configuration\Exceptions;
use Illuminate\Foundation\Configuration\Middleware;
use Symfony\Component\HttpKernel\Exception\HttpExceptionInterface;

return Application::configure(basePath: dirname(__DIR__))
    ->withRouting(
        web: __DIR__.'/../routes/web.php',
        api: __DIR__.'/../routes/api.php',
        commands: __DIR__.'/../routes/console.php',
        health: '/up',
    )
    ->withMiddleware(function (Middleware $middleware) {
        $middleware->api(prepend: [AssignRequestId::class]);
        $middleware->validateCsrfTokens(except: ['webhooks/*']);
        $middleware->alias([
            'staff.context' => EnsureStaffContext::class,
            'member.context' => EnsureMemberContext::class,
            'dev.tools' => EnsureDevToolsAccess::class,
        ]);
    })
    ->withExceptions(function (Exceptions $exceptions) {
        $exceptions->render(function (AuthenticationException $exception, $request) {
            return $request->is('api/*') ? ApiResponse::error('UNAUTHENTICATED', '请先登录', 401) : null;
        });
        $exceptions->render(function (ModelNotFoundException $exception, $request) {
            return $request->is('api/*') ? ApiResponse::error('RESOURCE_NOT_FOUND', '资源不存在', 404) : null;
        });
        $exceptions->render(function (HttpExceptionInterface $exception, $request) {
            if (! $request->is('api/*')) {
                return null;
            }
            $status = $exception->getStatusCode();
            $message = $exception->getMessage();
            $code = match ($message) {
                'PERMISSION_DENIED' => 'PERMISSION_DENIED',
                'STAFF_ACCESS_DENIED' => 'STAFF_ACCESS_DENIED',
                'ACCOUNT_DISABLED' => 'ACCOUNT_DISABLED',
                'TOKEN_AUDIENCE_INVALID' => 'TOKEN_AUDIENCE_INVALID',
                'STAFF_CONTEXT_REQUIRED' => 'STAFF_CONTEXT_REQUIRED',
                'PROFILE_VERSION_CONFLICT' => 'PROFILE_VERSION_CONFLICT',
                'PROFILE_VERSION_REQUIRED' => 'PROFILE_VERSION_REQUIRED',
                'PROFILE_FIELD_NOT_EDITABLE' => 'PROFILE_FIELD_NOT_EDITABLE',
                'LEGAL_DOCUMENTS_NOT_CONFIGURED' => 'LEGAL_DOCUMENTS_NOT_CONFIGURED',
                'REQUIRED_CONSENT_MISSING' => 'REQUIRED_CONSENT_MISSING',
                'MEMBER_VERSION_CONFLICT' => 'MEMBER_VERSION_CONFLICT',
                'INVALID_MEMBER_STATUS_TRANSITION' => 'INVALID_MEMBER_STATUS_TRANSITION',
                'MEMBER_OWNER_CONFLICT' => 'MEMBER_OWNER_CONFLICT',
                'CRM_MOBILE_CONFLICT' => 'CRM_MOBILE_CONFLICT',
                'CRM_FIELD_REQUIRED' => 'CRM_FIELD_REQUIRED',
                'CRM_FIELD_NOT_EDITABLE' => 'CRM_FIELD_NOT_EDITABLE',
                'CRM_FIELD_POLICY_LOCKED' => 'CRM_FIELD_POLICY_LOCKED',
                'MEMBER_RESTORE_BLOCKED' => 'MEMBER_RESTORE_BLOCKED',
                'MEMBER_NOT_ARCHIVED' => 'MEMBER_NOT_ARCHIVED',
                'INVALID_FILTER' => 'INVALID_FILTER',
                'MEMBER_APP_ACCESS_BLOCKED' => 'MEMBER_APP_ACCESS_BLOCKED',
                'MEMBER_RELATIONSHIP_CLOSED' => 'MEMBER_RELATIONSHIP_CLOSED',
                'MEMBER_PURCHASE_PROFILE_INCOMPLETE' => 'MEMBER_PURCHASE_PROFILE_INCOMPLETE',
                'ORDER_PAYMENT_INVALID' => 'ORDER_PAYMENT_INVALID',
                'ORDER_PAYMENT_EXPIRED' => 'ORDER_PAYMENT_EXPIRED',
                'ORDER_PAYMENT_UNAVAILABLE' => 'ORDER_PAYMENT_UNAVAILABLE',
                'PAYMENT_TRANSACTION_CONFLICT' => 'PAYMENT_TRANSACTION_CONFLICT',
                'PAYMENT_AMOUNT_MISMATCH' => 'PAYMENT_AMOUNT_MISMATCH',
                'PAYMENT_CURRENCY_MISMATCH' => 'PAYMENT_CURRENCY_MISMATCH',
                'PAYMENT_APPID_MISMATCH' => 'PAYMENT_APPID_MISMATCH',
                'PAYMENT_MERCHANT_MISMATCH' => 'PAYMENT_MERCHANT_MISMATCH',
                'TENANT_SITE_REQUIRED' => 'TENANT_SITE_REQUIRED',
                'MEMBER_LINK_CANDIDATE_BUSY' => 'MEMBER_LINK_CANDIDATE_BUSY',
                'MEMBER_LINK_STATE_CONFLICT' => 'MEMBER_LINK_STATE_CONFLICT',
                'MEMBER_LINK_VERSION_CONFLICT' => 'MEMBER_LINK_VERSION_CONFLICT',
                'MEMBER_LINK_EVIDENCE_EXPIRED' => 'MEMBER_LINK_EVIDENCE_EXPIRED',
                'MEMBER_LINK_DECISION_MISMATCH' => 'MEMBER_LINK_DECISION_MISMATCH',
                'MEMBER_LINK_SELF_REVIEW_FORBIDDEN' => 'MEMBER_LINK_SELF_REVIEW_FORBIDDEN',
                'MEMBER_LINK_LEAD_CONFLICT' => 'MEMBER_LINK_LEAD_CONFLICT',
                'MEMBER_LINK_EXPIRED' => 'MEMBER_LINK_EXPIRED',
                'VERSION_CONFLICT' => 'VERSION_CONFLICT',
                'CARD_PRODUCT_VERSION_CONFLICT' => 'CARD_PRODUCT_VERSION_CONFLICT',
                'CARD_PRODUCT_DELETE_FORBIDDEN' => 'CARD_PRODUCT_DELETE_FORBIDDEN',
                'CARD_PRODUCT_NOT_ISSUABLE' => 'CARD_PRODUCT_NOT_ISSUABLE',
                'COURSE_CATALOG_VERSION_CONFLICT' => 'COURSE_CATALOG_VERSION_CONFLICT',
                'COURSE_CATALOG_DELETE_FORBIDDEN' => 'COURSE_CATALOG_DELETE_FORBIDDEN',
                'COURSE_CATALOG_ARCHIVE_BLOCKED' => 'COURSE_CATALOG_ARCHIVE_BLOCKED',
                'COURSE_DEFAULT_ROOM_INVALID' => 'COURSE_DEFAULT_ROOM_INVALID',
                'COURSE_COACH_INVALID' => 'COURSE_COACH_INVALID',
                'ROOM_VERSION_CONFLICT' => 'ROOM_VERSION_CONFLICT',
                'ROOM_DELETE_FORBIDDEN' => 'ROOM_DELETE_FORBIDDEN',
                'SCHEDULE_SESSION_VERSION_CONFLICT' => 'SCHEDULE_SESSION_VERSION_CONFLICT',
                'BOOKING_POLICY_VERSION_CONFLICT' => 'BOOKING_POLICY_VERSION_CONFLICT',
                'BOOKING_DATE_OUT_OF_DISPLAY_WINDOW' => 'BOOKING_DATE_OUT_OF_DISPLAY_WINDOW',
                'BOOKING_DATE_OUT_OF_ADVANCE_WINDOW' => 'BOOKING_DATE_OUT_OF_ADVANCE_WINDOW',
                'BOOKING_CUTOFF_PASSED' => 'BOOKING_CUTOFF_PASSED',
                'BOOKING_CANCEL_CUTOFF_PASSED' => 'BOOKING_CANCEL_CUTOFF_PASSED',
                'BOOKING_DAILY_LIMIT_REACHED' => 'BOOKING_DAILY_LIMIT_REACHED',
                'BOOKING_SESSION_NOT_BOOKABLE' => 'BOOKING_SESSION_NOT_BOOKABLE',
                'BOOKING_SESSION_FULL' => 'BOOKING_SESSION_FULL',
                'BOOKING_SESSION_COUNT_INVALID' => 'BOOKING_SESSION_COUNT_INVALID',
                'BOOKING_CARD_NOT_PAYABLE' => 'BOOKING_CARD_NOT_PAYABLE',
                'BOOKING_CARD_PRICE_UNKNOWN' => 'BOOKING_CARD_PRICE_UNKNOWN',
                'CARD_BOOKING_TIME_RESTRICTED' => 'CARD_BOOKING_TIME_RESTRICTED',
                'CARD_BOOKING_LIMIT_REACHED' => 'CARD_BOOKING_LIMIT_REACHED',
                'CARD_ADVANCE_LIMIT_REACHED' => 'CARD_ADVANCE_LIMIT_REACHED',
                'CARD_REPEAT_BOOKING_DENIED' => 'CARD_REPEAT_BOOKING_DENIED',
                'CARD_CANCEL_LIMIT_REACHED' => 'CARD_CANCEL_LIMIT_REACHED',
                'CARD_BOOKING_FORBIDDEN_BY_ABSENCE' => 'CARD_BOOKING_FORBIDDEN_BY_ABSENCE',
                'APPOINTMENT_ALREADY_EXISTS' => 'APPOINTMENT_ALREADY_EXISTS',
                'APPOINTMENT_CANCEL_INVALID' => 'APPOINTMENT_CANCEL_INVALID',
                'SCHEDULE_SESSION_UPDATE_BLOCKED' => 'SCHEDULE_SESSION_UPDATE_BLOCKED',
                'SCHEDULE_SESSION_CANCEL_HAS_APPOINTMENTS' => 'SCHEDULE_SESSION_CANCEL_HAS_APPOINTMENTS',
                'COACH_PRIVATE_PROFILE_EXISTS' => 'COACH_PRIVATE_PROFILE_EXISTS',
                'COACH_PRIVATE_COACH_INVALID' => 'COACH_PRIVATE_COACH_INVALID',
                'COACH_PRIVATE_WINDOW_INVALID' => 'COACH_PRIVATE_WINDOW_INVALID',
                'COACH_PRIVATE_TIME_OUT_OF_WINDOW' => 'COACH_PRIVATE_TIME_OUT_OF_WINDOW',
                'COACH_PRIVATE_TIME_CONFLICT' => 'COACH_PRIVATE_TIME_CONFLICT',
                'COACH_PRIVATE_GROUP_OVERLAP' => 'COACH_PRIVATE_GROUP_OVERLAP',
                'COACH_PRIVATE_SUBJECT_REQUIRED' => 'COACH_PRIVATE_SUBJECT_REQUIRED',
                'SCHEDULE_SESSION_STATUS_CONFLICT' => 'SCHEDULE_SESSION_STATUS_CONFLICT',
                'SCHEDULE_SESSION_COURSE_INVALID' => 'SCHEDULE_SESSION_COURSE_INVALID',
                'SCHEDULE_SESSION_ROOM_INVALID' => 'SCHEDULE_SESSION_ROOM_INVALID',
                'SCHEDULE_SESSION_COACH_INVALID' => 'SCHEDULE_SESSION_COACH_INVALID',
                'SCHEDULE_SESSION_TIME_INVALID' => 'SCHEDULE_SESSION_TIME_INVALID',
                'SCHEDULE_SESSION_ROOM_CONFLICT' => 'SCHEDULE_SESSION_ROOM_CONFLICT',
                'MEMBER_CARD_ACTIVATION_INVALID' => 'MEMBER_CARD_ACTIVATION_INVALID',
                'MEMBER_CARD_BALANCE_ADJUST_INVALID' => 'MEMBER_CARD_BALANCE_ADJUST_INVALID',
                'MEMBER_CARD_COUNT_ADJUST_INVALID' => 'MEMBER_CARD_COUNT_ADJUST_INVALID',
                'INSUFFICIENT_BALANCE' => 'INSUFFICIENT_BALANCE',
                'INSUFFICIENT_COUNT' => 'INSUFFICIENT_COUNT',
                'FROZEN_CARD_DEBIT_BLOCKED' => 'FROZEN_CARD_DEBIT_BLOCKED',
                'MEMBER_CARD_FREEZE_INVALID' => 'MEMBER_CARD_FREEZE_INVALID',
                'MEMBER_CARD_UNFREEZE_INVALID' => 'MEMBER_CARD_UNFREEZE_INVALID',
                'MEMBER_CARD_HOLIDAY_INVALID' => 'MEMBER_CARD_HOLIDAY_INVALID',
                'MEMBER_CARD_VALIDITY_EXTENSION_INVALID' => 'MEMBER_CARD_VALIDITY_EXTENSION_INVALID',
                'MEMBER_CARD_ARCHIVE_INVALID' => 'MEMBER_CARD_ARCHIVE_INVALID',
                'MEMBER_CARD_RESTORE_INVALID' => 'MEMBER_CARD_RESTORE_INVALID',
                'MEMBER_CARD_ARCHIVED_MUTATION_BLOCKED' => 'MEMBER_CARD_ARCHIVED_MUTATION_BLOCKED',
                'MEMBER_CARD_VISIBILITY_INVALID' => 'MEMBER_CARD_VISIBILITY_INVALID',
                'LEDGER_ENTRY_NOT_CORRECTABLE' => 'LEDGER_ENTRY_NOT_CORRECTABLE',
                'LEDGER_ENTRY_ALREADY_REVERSED' => 'LEDGER_ENTRY_ALREADY_REVERSED',
                'TENANT_ID_REQUIRED' => 'TENANT_ID_REQUIRED',
                'BOOKING_SHARE_TOKEN_INVALID' => 'BOOKING_SHARE_TOKEN_INVALID',
                'BOOKING_SHARE_TOKEN_EXPIRED' => 'BOOKING_SHARE_TOKEN_EXPIRED',
                'STAFF_DEPARTURE_BLOCKED' => 'STAFF_DEPARTURE_BLOCKED',
                'STAFF_SELF_DEPARTURE_FORBIDDEN' => 'STAFF_SELF_DEPARTURE_FORBIDDEN',
                'SITE_OWNER_DEPARTURE_FORBIDDEN' => 'SITE_OWNER_DEPARTURE_FORBIDDEN',
                'STAFF_TRANSFER_NOT_INVITED' => 'STAFF_TRANSFER_NOT_INVITED',
                'STAFF_TRANSFER_INACTIVE' => 'STAFF_TRANSFER_INACTIVE',
                'SITE_OWNER_ALREADY_ASSIGNED' => 'SITE_OWNER_ALREADY_ASSIGNED',
                'STAFF_INVITE_SIGN_INVALID' => 'STAFF_INVITE_SIGN_INVALID',
                'STAFF_INVITE_SIGN_EXPIRED' => 'STAFF_INVITE_SIGN_EXPIRED',
                'STAFF_INVITE_INACTIVE' => 'STAFF_INVITE_INACTIVE',
                'STAFF_INVITE_ALREADY_ACCEPTED' => 'STAFF_INVITE_ALREADY_ACCEPTED',
                'STAFF_INVITE_WECHAT_CONFLICT' => 'STAFF_INVITE_WECHAT_CONFLICT',
                'STAFF_INVITE_ACCOUNT_MISMATCH' => 'STAFF_INVITE_ACCOUNT_MISMATCH',
                'STAFF_ROLE_SYSTEM_IMMUTABLE' => 'STAFF_ROLE_SYSTEM_IMMUTABLE',
                'STAFF_ROLE_PERMISSIONS_REQUIRED' => 'STAFF_ROLE_PERMISSIONS_REQUIRED',
                'STAFF_ROLE_PERMISSION_INVALID' => 'STAFF_ROLE_PERMISSION_INVALID',
                'PAYROLL_TIER_OVERLAP' => 'PAYROLL_TIER_OVERLAP',
                default => $status === 404 ? 'RESOURCE_NOT_FOUND' : 'REQUEST_REJECTED',
            };

            return ApiResponse::error($code, match ($code) {
                'PERMISSION_DENIED' => '没有执行该操作的权限',
                'STAFF_ACCESS_DENIED' => '当前账号没有有效员工身份',
                'ACCOUNT_DISABLED' => '账号已停用',
                'TOKEN_AUDIENCE_INVALID' => '当前登录会话不能访问员工功能',
                'STAFF_CONTEXT_REQUIRED' => '请选择要进入的员工组织',
                'PROFILE_VERSION_CONFLICT' => '资料已被其他设备修改，请刷新后重试',
                'PROFILE_VERSION_REQUIRED' => '修改资料必须提供当前版本',
                'PROFILE_FIELD_NOT_EDITABLE' => '该资料字段不允许会员自行修改',
                'LEGAL_DOCUMENTS_NOT_CONFIGURED' => '隐私协议尚未配置',
                'REQUIRED_CONSENT_MISSING' => '请阅读并同意当前隐私协议',
                'MEMBER_VERSION_CONFLICT' => '会员资料已被其他人修改，请刷新后重试',
                'INVALID_MEMBER_STATUS_TRANSITION' => '当前会员状态不允许执行该操作',
                'MEMBER_OWNER_CONFLICT' => '会员已被其他顾问认领或资料已更新',
                'CRM_MOBILE_CONFLICT' => '该手机号已存在于当前租户，不会自动合并会员',
                'CRM_FIELD_REQUIRED' => '缺少租户要求的必填资料字段',
                'CRM_FIELD_NOT_EDITABLE' => '该资料字段不允许员工修改',
                'CRM_FIELD_POLICY_LOCKED' => '该字段的可见性或必填规则不可修改',
                'MEMBER_RESTORE_BLOCKED' => '恢复失败：当前手机号已被其他会员占用',
                'MEMBER_NOT_ARCHIVED' => '该会员未处于归档状态',
                'INVALID_FILTER' => '筛选参数无效',
                'MEMBER_APP_ACCESS_BLOCKED' => '当前场馆已限制该会员账号访问，请联系场馆处理',
                'MEMBER_RELATIONSHIP_CLOSED' => '当前会员关系已关闭，请联系场馆处理',
                'MEMBER_PURCHASE_PROFILE_INCOMPLETE' => '购卡前请先完善会员资料',
                'ORDER_PAYMENT_INVALID' => '当前订单状态不允许支付',
                'ORDER_PAYMENT_EXPIRED' => '订单已超过支付时间，请重新下单',
                'ORDER_PAYMENT_UNAVAILABLE' => '微信支付暂不可用，请稍后再试',
                'PAYMENT_TRANSACTION_CONFLICT' => '支付流水与订单记录不一致',
                'PAYMENT_AMOUNT_MISMATCH' => '支付金额与订单金额不一致',
                'PAYMENT_CURRENCY_MISMATCH' => '支付币种与订单不一致',
                'PAYMENT_APPID_MISMATCH' => '支付应用与订单不一致',
                'PAYMENT_MERCHANT_MISMATCH' => '支付商户与订单不一致',
                'TENANT_SITE_REQUIRED' => '请选择场馆后再试',
                'MEMBER_LINK_CANDIDATE_BUSY' => '该场馆档案正在处理其他关联申请',
                'MEMBER_LINK_STATE_CONFLICT' => '关联申请状态已变化，请刷新后重试',
                'MEMBER_LINK_VERSION_CONFLICT' => '关联申请已被其他人处理，请刷新后重试',
                'MEMBER_LINK_EVIDENCE_EXPIRED' => '已验证手机号已变化，请重新发起关联',
                'MEMBER_LINK_DECISION_MISMATCH' => '会员确认结果与本次审核操作不一致',
                'MEMBER_LINK_SELF_REVIEW_FORBIDDEN' => '不能审核本人发起的会员档案关联',
                'MEMBER_LINK_LEAD_CONFLICT' => '潜客档案已被关联或发生冲突，请刷新后处理',
                'MEMBER_LINK_EXPIRED' => '关联申请已过期，请重新发起',
                'VERSION_CONFLICT' => '数据已被其他人修改，请刷新后重试',
                'CARD_PRODUCT_VERSION_CONFLICT' => '卡种模板已被其他人修改，请刷新后重试',
                'CARD_PRODUCT_DELETE_FORBIDDEN' => '卡种模板不支持物理删除，请使用归档',
                'CARD_PRODUCT_NOT_ISSUABLE' => '卡种模板已归档，无法开卡',
                'COURSE_CATALOG_VERSION_CONFLICT' => '课程模板已被其他人修改，请刷新后重试',
                'COURSE_CATALOG_DELETE_FORBIDDEN' => '课程模板不支持物理删除，请使用归档',
                'COURSE_CATALOG_ARCHIVE_BLOCKED' => '课程存在排课记录，无法归档',
                'COURSE_DEFAULT_ROOM_INVALID' => '默认教室无效或不可用',
                'COURSE_COACH_INVALID' => '指定教练无效或不可用',
                'ROOM_VERSION_CONFLICT' => '教室资料已被其他人修改，请刷新后重试',
                'ROOM_DELETE_FORBIDDEN' => '教室不支持物理删除，请使用归档',
                'SCHEDULE_SESSION_VERSION_CONFLICT' => '排课已被其他人修改，请刷新后重试',
                'BOOKING_POLICY_VERSION_CONFLICT' => '预约规则已被其他人修改，请刷新后重试',
                'BOOKING_DATE_OUT_OF_DISPLAY_WINDOW' => '所选日期超出可预约日历显示范围',
                'BOOKING_DATE_OUT_OF_ADVANCE_WINDOW' => '所选课程超出可提前预约天数',
                'BOOKING_CUTOFF_PASSED' => '已超过预约截止时间',
                'BOOKING_CANCEL_CUTOFF_PASSED' => '已超过取消预约截止时间',
                'BOOKING_DAILY_LIMIT_REACHED' => '已达到当日预约次数上限',
                'BOOKING_SESSION_NOT_BOOKABLE' => '当前课程不可预约',
                'BOOKING_SESSION_FULL' => '课程名额已满且未开启排队',
                'BOOKING_SESSION_COUNT_INVALID' => '课程预约人数异常',
                'BOOKING_CARD_NOT_PAYABLE' => '当前会员卡不可用于该课程预约',
                'CARD_BOOKING_TIME_RESTRICTED' => '该卡不在可用时段内，无法预约此课',
                'CARD_BOOKING_LIMIT_REACHED' => '已达到该卡的预约次数上限',
                'CARD_ADVANCE_LIMIT_REACHED' => '已达到该卡可提前预约的次数上限',
                'CARD_REPEAT_BOOKING_DENIED' => '该卡不允许重复预约同一课程',
                'CARD_CANCEL_LIMIT_REACHED' => '已达到该卡的取消次数上限',
                'CARD_BOOKING_FORBIDDEN_BY_ABSENCE' => '因旷课处罚，该卡暂时无法预约',
                'BOOKING_CARD_PRICE_UNKNOWN' => '无法确定储值卡扣费金额',
                'APPOINTMENT_ALREADY_EXISTS' => '您已预约或排队该课程',
                'APPOINTMENT_CANCEL_INVALID' => '当前预约状态不允许取消',
                'SCHEDULE_SESSION_UPDATE_BLOCKED' => '容量不能小于已预约人数，且已有预约时不可更改课程类型',
                'SCHEDULE_SESSION_CANCEL_HAS_APPOINTMENTS' => '该课已有会员预约，请先手动取消约课后再删除',
                'COACH_PRIVATE_PROFILE_EXISTS' => '该教练已有私教档案，请直接编辑',
                'COACH_PRIVATE_COACH_INVALID' => '教练无效或已离职',
                'COACH_PRIVATE_WINDOW_INVALID' => '预约时段结束时间需晚于开始时间',
                'COACH_PRIVATE_TIME_OUT_OF_WINDOW' => '不在教练可约时段内',
                'COACH_PRIVATE_TIME_CONFLICT' => '该时段教练已有安排',
                'COACH_PRIVATE_GROUP_OVERLAP' => '该时段与团课重合，请确认后重试',
                'COACH_PRIVATE_SUBJECT_REQUIRED' => '请选择私教课目',
                'SCHEDULE_SESSION_STATUS_CONFLICT' => '当前排课状态不允许执行该操作',
                'SCHEDULE_SESSION_COURSE_INVALID' => '课程无效或不属于当前场馆',
                'SCHEDULE_SESSION_ROOM_INVALID' => '教室无效或不属于当前场馆',
                'SCHEDULE_SESSION_COACH_INVALID' => '指定教练无效或不可用',
                'SCHEDULE_SESSION_TIME_INVALID' => '结束时间必须晚于开始时间',
                'SCHEDULE_SESSION_ROOM_CONFLICT' => '教室在该时段已有排课',
                'MEMBER_CARD_ACTIVATION_INVALID' => '当前会员卡状态不允许激活',
                'MEMBER_CARD_BALANCE_ADJUST_INVALID' => '当前会员卡不支持余额调整',
                'MEMBER_CARD_COUNT_ADJUST_INVALID' => '当前会员卡不支持次数调整',
                'INSUFFICIENT_BALANCE' => '余额不足，无法扣减',
                'INSUFFICIENT_COUNT' => '剩余次数不足，无法扣减',
                'FROZEN_CARD_DEBIT_BLOCKED' => '会员卡已冻结，无法扣减',
                'MEMBER_CARD_FREEZE_INVALID' => '当前会员卡状态不允许冻结',
                'MEMBER_CARD_UNFREEZE_INVALID' => '当前会员卡未处于冻结状态',
                'MEMBER_CARD_HOLIDAY_INVALID' => '当前会员卡状态不允许请假操作',
                'MEMBER_CARD_VALIDITY_EXTENSION_INVALID' => '当前会员卡不支持有效期调整',
                'MEMBER_CARD_ARCHIVE_INVALID' => '当前会员卡状态不允许归档',
                'MEMBER_CARD_RESTORE_INVALID' => '当前会员卡状态不允许恢复',
                'MEMBER_CARD_ARCHIVED_MUTATION_BLOCKED' => '已归档会员卡不支持余额或次数调整',
                'MEMBER_CARD_VISIBILITY_INVALID' => '当前会员卡状态不允许变更可见性',
                'LEDGER_ENTRY_NOT_CORRECTABLE' => '该流水记录不支持冲正',
                'LEDGER_ENTRY_ALREADY_REVERSED' => '该流水记录已被冲正',
                'TENANT_ID_REQUIRED' => '请提供租户标识',
                'BOOKING_SHARE_TOKEN_INVALID' => '分享链接无效或已损坏',
                'BOOKING_SHARE_TOKEN_EXPIRED' => '分享链接已过期',
                'STAFF_DEPARTURE_BLOCKED' => '该员工仍有未来课程或预约，无法离职',
                'STAFF_SELF_DEPARTURE_FORBIDDEN' => '不能将自己设为离职',
                'SITE_OWNER_DEPARTURE_FORBIDDEN' => '场馆所有者不能直接离职，请先转让所有权',
                'STAFF_TRANSFER_NOT_INVITED' => '请先邀请该员工完成微信绑定后再转让',
                'STAFF_TRANSFER_INACTIVE' => '只能将所有权转让给在职员工',
                'SITE_OWNER_ALREADY_ASSIGNED' => '该员工已是场馆所有者',
                'STAFF_INVITE_SIGN_INVALID' => '邀请链接无效或已损坏',
                'STAFF_INVITE_SIGN_EXPIRED' => '邀请链接已过期',
                'STAFF_INVITE_INACTIVE' => '该员工邀请已失效',
                'STAFF_INVITE_ALREADY_ACCEPTED' => '该员工邀请已被接受',
                'STAFF_INVITE_WECHAT_CONFLICT' => '当前微信已绑定其他账号',
                'STAFF_INVITE_ACCOUNT_MISMATCH' => '当前登录账号与邀请不匹配',
                'STAFF_ROLE_SYSTEM_IMMUTABLE' => '系统角色不可修改',
                'STAFF_ROLE_PERMISSIONS_REQUIRED' => '请至少选择一个权限',
                'STAFF_ROLE_PERMISSION_INVALID' => '包含无效的权限项',
                'PAYROLL_TIER_OVERLAP' => '会籍提成阶梯区间不能重叠',
                'RESOURCE_NOT_FOUND' => '资源不存在',
                default => '请求被拒绝',
            }, $status);
        });
    })->create();
