packages:
  - apps/*
  - packages/*

onlyBuiltDependencies:
  - "@parcel/watcher"
  - core-js
  - esbuild
  - vue-demi
allowBuilds:
  '@parcel/watcher': true
  core-js: true
  esbuild: true
  vue-demi: true
minimumReleaseAgeExclude:
  - '@vue/language-core@3.3.11'
  - element-plus@2.14.5
  - vue-tsc@3.3.11
