import type { ResourceDefinition, ResourceKey } from "@/types/admin";

const resources: Record<ResourceKey, ResourceDefinition> = {
  members: {
    key: "members",
    title: "会员管理",
    eyebrow: "CRM",
    description: "跨租户查看平台会员档案；列表来自超级管理员只读接口。",
    permission: "member.read",
    scope: "site",
    primaryOperation: "listAdminMembers",
    operations: ["listAdminMembers"],
    columns: [
      { key: "name", label: "会员", minWidth: 150 },
      { key: "mobile", label: "手机号", minWidth: 140 },
      { key: "owner", label: "所属租户", minWidth: 140 },
      { key: "cards", label: "所属场馆", minWidth: 140 },
      { key: "lastVisit", label: "加入时间", type: "date", minWidth: 130 },
      { key: "status", label: "状态", type: "status", width: 100 },
    ],
    actions: [
      { key: "view", label: "查看", permission: "member.read" },
      { key: "edit", label: "编辑", permission: "member.update" },
    ],
    rows: [
      { id: "M-10882", name: "周雨晴", mobile: "138****2064", owner: "顾教练", cards: 2, lastVisit: "今天 09:42", status: "活跃" },
      { id: "M-10879", name: "陈屿", mobile: "186****7318", owner: "林店长", cards: 1, lastVisit: "昨天 19:10", status: "活跃" },
      { id: "M-10853", name: "许婉宁", mobile: "159****1882", owner: "—", cards: 0, lastVisit: "8月18日", status: "潜客" },
      { id: "M-10796", name: "江嘉树", mobile: "177****4120", owner: "王会籍", cards: 1, lastVisit: "8月12日", status: "待跟进" },
      { id: "M-10742", name: "苏蔓", mobile: "135****9231", owner: "顾教练", cards: 3, lastVisit: "8月8日", status: "活跃" },
    ],
  },
  courses: {
    key: "courses",
    title: "课程目录",
    eyebrow: "CATALOG",
    description: "维护团课、私教课程及其展示和适用范围。",
    permission: "course-catalog.read",
    scope: "site",
    primaryOperation: "listStaffCourses",
    operations: ["listStaffCourses", "getStaffCourse", "createStaffCourse", "updateStaffCourse"],
    columns: [
      { key: "name", label: "课程", minWidth: 180 },
      { key: "type", label: "类型", width: 100 },
      { key: "duration", label: "时长", width: 100 },
      { key: "coaches", label: "适用教练", width: 110 },
      { key: "updatedAt", label: "最近更新", minWidth: 130 },
      { key: "status", label: "状态", type: "status", width: 100 },
    ],
    actions: [{ key: "view", label: "查看" }, { key: "edit", label: "编辑", permission: "course-catalog.update" }],
    rows: [
      { id: "C-201", name: "燃脂搏击", type: "团课", duration: "60 分钟", coaches: 4, updatedAt: "今天 10:20", status: "启用" },
      { id: "C-198", name: "流瑜伽", type: "团课", duration: "55 分钟", coaches: 3, updatedAt: "8月20日", status: "启用" },
      { id: "C-182", name: "一对一体态评估", type: "私教", duration: "60 分钟", coaches: 7, updatedAt: "8月18日", status: "启用" },
      { id: "C-169", name: "核心进阶", type: "团课", duration: "45 分钟", coaches: 2, updatedAt: "8月5日", status: "草稿" },
    ],
  },
  schedules: {
    key: "schedules",
    title: "排课管理",
    eyebrow: "SCHEDULING",
    description: "按日历查看课程场次、容量和教练安排。调课与停课由后端进行冲突校验。",
    permission: "schedule.read",
    scope: "site",
    primaryOperation: "listStaffScheduleSessions",
    operations: ["listStaffScheduleSessions", "getStaffScheduleSession", "createStaffScheduleSession"],
    columns: [
      { key: "time", label: "开始时间", minWidth: 150 },
      { key: "course", label: "课程", minWidth: 160 },
      { key: "coach", label: "教练", width: 110 },
      { key: "room", label: "教室", width: 110 },
      { key: "capacity", label: "预约/容量", width: 110 },
      { key: "status", label: "状态", type: "status", width: 100 },
    ],
    actions: [{ key: "view", label: "详情" }, { key: "adjust", label: "调课", permission: "schedule.update" }],
    rows: [
      { id: "S-8821", time: "今天 18:30", course: "燃脂搏击", coach: "顾晨", room: "A 教室", capacity: "16 / 20", status: "预约中" },
      { id: "S-8822", time: "今天 19:40", course: "流瑜伽", coach: "林悦", room: "瑜伽房", capacity: "12 / 16", status: "预约中" },
      { id: "S-8823", time: "今天 20:30", course: "核心进阶", coach: "郑屿", room: "B 教室", capacity: "8 / 12", status: "未开始" },
    ],
  },
  appointments: {
    key: "appointments",
    title: "预约与履约",
    eyebrow: "BOOKING",
    description: "查看预约、候补、签到和旷课状态，席位结果以服务端事务结果为准。",
    permission: "booking.read",
    scope: "site",
    primaryOperation: "getStaffBookingDailyBoard",
    operations: ["getStaffBookingDailyBoard", "listStaffSessionAppointments", "listStaffSessionWaitlist"],
    columns: [
      { key: "member", label: "会员", minWidth: 140 },
      { key: "session", label: "场次", minWidth: 180 },
      { key: "bookedAt", label: "预约时间", minWidth: 140 },
      { key: "card", label: "使用权益", minWidth: 160 },
      { key: "status", label: "履约状态", type: "status", width: 110 },
    ],
    actions: [{ key: "view", label: "查看" }, { key: "checkin", label: "签到", permission: "booking.check-in" }],
    rows: [
      { id: "A-60931", member: "周雨晴", session: "燃脂搏击 · 18:30", bookedAt: "今天 08:15", card: "团课次卡", status: "已预约" },
      { id: "A-60918", member: "陈屿", session: "流瑜伽 · 19:40", bookedAt: "昨天 21:04", card: "月度畅练卡", status: "已预约" },
      { id: "A-60892", member: "苏蔓", session: "燃脂搏击 · 18:30", bookedAt: "昨天 12:30", card: "团课次卡", status: "候补" },
    ],
  },
  cards: {
    key: "cards",
    title: "会员卡与权益",
    eyebrow: "ENTITLEMENT",
    description: "持卡余额用于快速展示，真实权益以不可变流水为准。",
    permission: "member-card.read",
    scope: "site",
    primaryOperation: "listStaffMemberCards",
    operations: ["listStaffMemberCards", "getStaffMemberCard", "listStaffMemberCardLedgerEntries"],
    columns: [
      { key: "member", label: "会员", minWidth: 130 },
      { key: "product", label: "卡产品", minWidth: 180 },
      { key: "balance", label: "剩余权益", minWidth: 130 },
      { key: "expires", label: "有效期至", type: "date", minWidth: 130 },
      { key: "status", label: "状态", type: "status", width: 100 },
    ],
    actions: [{ key: "ledger", label: "流水" }, { key: "adjust", label: "调整", permission: "member-card.adjust" }],
    rows: [
      { id: "MC-30219", member: "周雨晴", product: "团课 30 次卡", balance: "18 次", expires: "2027-03-18", status: "生效" },
      { id: "MC-30202", member: "陈屿", product: "月度畅练卡", balance: "24 天", expires: "2026-09-15", status: "生效" },
      { id: "MC-30177", member: "江嘉树", product: "私教 12 节", balance: "2 节", expires: "2026-08-31", status: "将到期" },
    ],
  },
  orders: {
    key: "orders",
    title: "订单管理",
    eyebrow: "COMMERCE",
    description: "订单金额、补正与退款均由服务端规则计算，后台只提交业务意图。",
    permission: "order.read",
    scope: "site",
    primaryOperation: "listMemberCardOrders",
    operations: ["listMemberCardOrders", "correctMemberCardOrderAmount", "voidMemberCardOrder"],
    columns: [
      { key: "orderNo", label: "订单号", minWidth: 180 },
      { key: "member", label: "会员", minWidth: 130 },
      { key: "item", label: "商品", minWidth: 180 },
      { key: "amount", label: "实付金额", type: "money", width: 120 },
      { key: "createdAt", label: "创建时间", minWidth: 150 },
      { key: "status", label: "状态", type: "status", width: 100 },
    ],
    actions: [{ key: "view", label: "详情" }, { key: "correct", label: "补正", permission: "order.correct" }],
    rows: [
      { id: "O-99218", orderNo: "SG2026082200138", member: "周雨晴", item: "团课 30 次卡", amount: "¥ 2,680.00", createdAt: "今天 10:12", status: "已支付" },
      { id: "O-99196", orderNo: "SG2026082100091", member: "陈屿", item: "月度畅练卡", amount: "¥ 699.00", createdAt: "昨天 16:33", status: "已支付" },
      { id: "O-99172", orderNo: "SG2026082100067", member: "许婉宁", item: "新人体验课", amount: "¥ 0.00", createdAt: "昨天 11:08", status: "已完成" },
    ],
  },
  sites: {
    key: "sites",
    title: "租户与场馆",
    eyebrow: "ORGANIZATION",
    description: "跨租户查看平台客户、场馆、会员和员工规模。",
    permission: "site.read",
    scope: "tenant",
    primaryOperation: "listAdminTenants",
    operations: ["listAdminTenants"],
    columns: [
      { key: "name", label: "租户", minWidth: 180 },
      { key: "manager", label: "租户编码", width: 120 },
      { key: "members", label: "会员数", type: "number", width: 100 },
      { key: "todayClasses", label: "场馆数", type: "number", width: 100 },
      { key: "address", label: "员工规模", minWidth: 140 },
      { key: "status", label: "状态", type: "status", width: 100 },
    ],
    actions: [{ key: "view", label: "查看" }, { key: "edit", label: "配置", permission: "site.update" }],
    rows: [
      { id: "SITE-1", name: "滨江旗舰店", manager: "林乔", members: 1286, todayClasses: 18, address: "滨江区江南大道 1788 号", status: "营业中" },
      { id: "SITE-2", name: "城西社区店", manager: "王茗", members: 642, todayClasses: 9, address: "西湖区文二西路 318 号", status: "营业中" },
      { id: "SITE-3", name: "钱江新城店", manager: "陈昊", members: 0, todayClasses: 0, address: "上城区民心路 88 号", status: "筹备中" },
    ],
  },
  staff: {
    key: "staff",
    title: "员工与权限",
    eyebrow: "ACCESS",
    description: "管理员工身份、任职场馆和角色；实际授权始终由服务端校验。",
    permission: "staff.read",
    scope: "tenant",
    primaryOperation: "listStaffDirectory",
    operations: ["listStaffDirectory", "getStaffDirectory", "listStaffRoles", "getStaffPermissionCatalog"],
    columns: [
      { key: "name", label: "员工", minWidth: 140 },
      { key: "employeeNo", label: "工号", width: 110 },
      { key: "role", label: "角色", minWidth: 130 },
      { key: "site", label: "主要场馆", minWidth: 150 },
      { key: "lastActive", label: "最近活跃", minWidth: 130 },
      { key: "status", label: "状态", type: "status", width: 100 },
    ],
    actions: [{ key: "view", label: "查看" }, { key: "role", label: "权限", permission: "staff.role.update" }],
    rows: [
      { id: "ST-1001", name: "林乔", employeeNo: "ADMIN001", role: "租户所有者", site: "全部场馆", lastActive: "刚刚", status: "在职" },
      { id: "ST-1036", name: "顾晨", employeeNo: "COACH036", role: "教练", site: "滨江旗舰店", lastActive: "12 分钟前", status: "在职" },
      { id: "ST-1049", name: "王茗", employeeNo: "MGR049", role: "店长", site: "城西社区店", lastActive: "今天 08:31", status: "在职" },
    ],
  },
  reports: {
    key: "reports",
    title: "经营报表",
    eyebrow: "REPORTING",
    description: "指标由服务端事实表和汇总表生成，可下钻到订单、权益和预约记录。",
    permission: "report.read",
    scope: "site",
    primaryOperation: "getStaffReportDashboard",
    operations: ["getStaffReportDashboard", "getStaffFinanceReport", "getStaffCourseReport"],
    columns: [
      { key: "metric", label: "指标", minWidth: 180 },
      { key: "today", label: "今日", minWidth: 120 },
      { key: "month", label: "本月", minWidth: 120 },
      { key: "trend", label: "环比", minWidth: 110 },
      { key: "source", label: "事实来源", minWidth: 180 },
      { key: "status", label: "数据状态", type: "status", width: 110 },
    ],
    actions: [{ key: "drill", label: "下钻" }, { key: "export", label: "导出", permission: "report.export" }],
    rows: [
      { id: "R-1", metric: "实收金额", today: "¥ 8,420", month: "¥ 186,320", trend: "+12.4%", source: "支付与金额补正", status: "已更新" },
      { id: "R-2", metric: "到课人次", today: 96, month: 2138, trend: "+5.8%", source: "预约履约", status: "已更新" },
      { id: "R-3", metric: "新增会员", today: 7, month: 128, trend: "+9.2%", source: "会员档案", status: "已更新" },
    ],
  },
  audit: {
    key: "audit",
    title: "操作审计",
    eyebrow: "AUDIT",
    description: "追踪敏感写操作的操作者、对象、请求编号与结果。审计记录只读。",
    permission: "audit.read",
    scope: "tenant",
    primaryOperation: "listAdminAuditLogs",
    operations: ["listAdminAuditLogs"],
    columns: [
      { key: "time", label: "时间", minWidth: 150 },
      { key: "actor", label: "操作者", width: 120 },
      { key: "action", label: "操作", minWidth: 160 },
      { key: "subject", label: "对象", minWidth: 180 },
      { key: "requestId", label: "请求编号", minWidth: 190 },
      { key: "status", label: "结果", type: "status", width: 90 },
    ],
    actions: [{ key: "view", label: "详情" }],
    rows: [
      { id: "AE-78291", time: "今天 10:22:18", actor: "林乔", action: "调整会员卡次数", subject: "周雨晴 · 团课 30 次卡", requestId: "req_4f8d...91c2", status: "成功" },
      { id: "AE-78288", time: "今天 10:14:03", actor: "王茗", action: "修改排课教练", subject: "流瑜伽 · 8月23日", requestId: "req_911a...e048", status: "成功" },
      { id: "AE-78270", time: "今天 09:48:51", actor: "顾晨", action: "预约签到", subject: "陈屿 · 燃脂搏击", requestId: "req_c3f2...7710", status: "成功" },
    ],
  },
};

export function getResource(key: string) {
  return resources[key as ResourceKey];
}

export const resourceRegistry = resources;
