<?php

use App\Http\Controllers\Api\V1\AuthController;
use App\Http\Controllers\Api\V1\MeController;
use App\Http\Controllers\Api\V1\MemberContextController;
use App\Http\Controllers\Api\V1\MemberHomeController;
use App\Http\Controllers\Api\V1\MemberMineController;
use App\Http\Controllers\Api\V1\MemberMonthlyRankingController;
use App\Http\Controllers\Api\V1\MemberNoticeController;
use App\Http\Controllers\Api\V1\MemberOfficialAccountFollowController;
use App\Http\Controllers\Api\V1\MemberPointLedgerController;
use App\Http\Controllers\Api\V1\MemberCardProductController;
use App\Http\Controllers\Api\V1\MemberCardTransferController;
use App\Http\Controllers\Api\V1\MemberStatsController;
use App\Http\Controllers\Api\V1\MemberMemberCardOrderController;
use App\Http\Controllers\Api\V1\MemberMemberCardController;
use App\Http\Controllers\Api\V1\MemberLinkController;
use App\Http\Controllers\Api\V1\MemberProfileController;
use App\Http\Controllers\Api\V1\MemberSiteController;
use App\Http\Controllers\Api\V1\MemberTagController;
use App\Http\Controllers\Api\V1\SiteController;
use App\Http\Controllers\Api\V1\StaffCardProductCrossSiteController;
use App\Http\Controllers\Api\V1\StaffCardProductController;
use App\Http\Controllers\Api\V1\StaffCoachPrivateProfileController;
use App\Http\Controllers\Api\V1\StaffCourseController;
use App\Http\Controllers\Api\V1\StaffRoomController;
use App\Http\Controllers\Api\V1\MemberAppointmentController;
use App\Http\Controllers\Api\V1\MemberBookingCatalogController;
use App\Http\Controllers\Api\V1\MemberPrivateCoachController;
use App\Http\Controllers\Api\V1\MemberBookingPayableCardController;
use App\Http\Controllers\Api\V1\MemberBookingSessionController;
use App\Http\Controllers\Api\V1\StaffAppointmentController;
use App\Http\Controllers\Api\V1\StaffBookingDailyBoardController;
use App\Http\Controllers\Api\V1\StaffBookingPolicyController;
use App\Http\Controllers\Api\V1\StaffScheduleSessionController;
use App\Http\Controllers\Api\V1\StaffScheduleBatchController;
use App\Http\Controllers\Api\V1\StaffScheduleDisplayController;
use App\Http\Controllers\Api\V1\StaffScheduleExtrasController;
use App\Http\Controllers\Api\V1\StaffMemberCardBatchController;
use App\Http\Controllers\Api\V1\StaffMemberCardController;
use App\Http\Controllers\Api\V1\StaffMemberCardOrderController;
use App\Http\Controllers\Api\V1\StaffMemberCardReminderController;
use App\Http\Controllers\Api\V1\StaffCrmConfigController;
use App\Http\Controllers\Api\V1\StaffLegalConfigController;
use App\Http\Controllers\Api\V1\StaffMemberExperienceController;
use App\Http\Controllers\Api\V1\StaffNotificationChannelController;
use App\Http\Controllers\Api\V1\StaffSiteClosureController;
use App\Http\Controllers\Api\V1\StaffSiteNoticeController;
use App\Http\Controllers\Api\V1\StaffTenantSettingsController;
use App\Http\Controllers\Api\V1\StaffVacationController;
use App\Http\Controllers\Api\V1\StaffCrmDashboardController;
use App\Http\Controllers\Api\V1\StaffDashboardController;
use App\Http\Controllers\Api\V1\StaffReportDashboardController;
use App\Http\Controllers\Api\V1\StaffReportCourseController;
use App\Http\Controllers\Api\V1\StaffReportFinanceController;
use App\Http\Controllers\Api\V1\StaffExportController;
use App\Http\Controllers\Api\V1\StaffNotificationReminderController;
use App\Http\Controllers\Api\V1\StaffReportCoachController;
use App\Http\Controllers\Api\V1\StaffReportCardSalesController;
use App\Http\Controllers\Api\V1\StaffReportCardAnalyzeController;
use App\Http\Controllers\Api\V1\StaffReportChangeLogController;
use App\Http\Controllers\Api\V1\StaffReportRankingController;
use App\Http\Controllers\Api\V1\IdentityWechatController;
use App\Http\Controllers\Api\V1\StaffDirectoryController;
use App\Http\Controllers\Api\V1\StaffInviteController;
use App\Http\Controllers\Api\V1\StaffRoleController;
use App\Http\Controllers\Api\V1\StaffMemberController;
use App\Http\Controllers\Api\V1\StaffConstantsController;
use App\Http\Controllers\Api\V1\StaffChainController;
use App\Http\Controllers\Api\V1\StaffCheckInController;
use App\Http\Controllers\Api\V1\StaffSupportController;
use App\Http\Controllers\Api\V1\StaffPayrollConfigController;
use App\Http\Controllers\Api\V1\StaffPayrollReportController;
use App\Http\Controllers\Api\V1\StaffPlatformSubscriptionController;
use App\Http\Controllers\Api\V1\StaffPointsConfigController;
use App\Http\Controllers\Api\V1\StaffLedgerReconciliationController;
use App\Http\Controllers\Api\V1\StaffReportCalendarController;
use App\Http\Controllers\Api\V1\StaffProfileController;
use App\Http\Controllers\Api\V1\StaffSharingController;
use App\Http\Controllers\Api\V1\StaffSiteProfileController;
use App\Http\Controllers\Api\V1\PublicBookingShareController;
use App\Http\Controllers\Api\V1\PublicBookingWarmHintController;
use App\Http\Controllers\Api\V1\StaffBookingHistoryController;
use App\Http\Controllers\Api\V1\StaffMemberLinkController;
use App\Support\ApiResponse;
use Illuminate\Support\Facades\Route;

Route::get('/v1/health', function () {
    return ApiResponse::success([
        'service' => 'songguo-next-api',
        'status' => 'ok',
    ]);
});

Route::post('/v1/auth/wechat/login', [AuthController::class, 'login']);

Route::get('/v1/staff/invites/{sign}', [StaffInviteController::class, 'preview'])
    ->where('sign', '[A-Za-z0-9_-]+\.[A-Za-z0-9_-]+');

Route::prefix('/v1/public')->group(function () {
    Route::get('/booking/share/sessions/{token}', [PublicBookingShareController::class, 'show'])
        ->where('token', '[A-Za-z0-9_-]+\.[A-Za-z0-9_-]+');
    Route::get('/booking/warm-hint/sites/{site}', [PublicBookingWarmHintController::class, 'show']);
});

Route::middleware('auth:sanctum')->prefix('/v1')->group(function () {
    Route::post('/auth/logout', [AuthController::class, 'logout']);
    Route::get('/me', MeController::class);
    Route::post('/identity/wechat/unionid', [IdentityWechatController::class, 'resolveUnionId']);
    Route::post('/staff/invites/{sign}/accept', [StaffInviteController::class, 'accept'])
        ->where('sign', '[A-Za-z0-9_-]+\.[A-Za-z0-9_-]+');
    Route::apiResource('sites', SiteController::class)->middleware('staff.context');
    Route::middleware('member.context')->prefix('/member')->group(function () {
        Route::get('/onboarding', [MemberProfileController::class, 'show']);
        Route::get('/profile', [MemberProfileController::class, 'readProfile']);
        Route::get('/profile/purchase-gate', [MemberProfileController::class, 'purchaseGate']);
        Route::patch('/profile/ranking-opt-in', [MemberProfileController::class, 'updateRankingOptIn']);
        Route::match(['put', 'patch'], '/profile', [MemberProfileController::class, 'update']);
        Route::post('/profile/avatar', [MemberProfileController::class, 'uploadAvatar']);
        Route::post('/profile/verify-mobile', [MemberProfileController::class, 'verifyMobile']);
        Route::get('/sites', [MemberContextController::class, 'sites']);
        Route::get('/memberships', [MemberContextController::class, 'memberships']);
        Route::post('/memberships', [MemberContextController::class, 'join']);
        Route::get('/legal-documents', [MemberContextController::class, 'legalDocuments']);
        Route::get('/orders', [MemberMemberCardOrderController::class, 'index']);
        Route::get('/orders/{order}', [MemberMemberCardOrderController::class, 'show']);
        Route::post('/orders/{order}/sync-payment', [MemberMemberCardOrderController::class, 'syncPayment']);
        Route::get('/sites/{site}/public-detail', [MemberSiteController::class, 'show']);
        Route::get('/sites/{site}/closure-status', [MemberSiteController::class, 'closureStatus']);
        Route::get('/card-transfers/{token}', [MemberCardTransferController::class, 'show'])
            ->where('token', '[A-Za-z0-9_-]+\.[A-Za-z0-9_-]+');
        Route::post('/card-transfers/{token}/claim', [MemberCardTransferController::class, 'claim'])
            ->where('token', '[A-Za-z0-9_-]+\.[A-Za-z0-9_-]+');
        Route::get('/member-link-requests', [MemberLinkController::class, 'index']);
        Route::post('/member-link-requests/{linkRequest}/decision', [MemberLinkController::class, 'decide']);
        Route::get('/home', [MemberHomeController::class, 'show']);
        Route::get('/mine', [MemberMineController::class, 'show']);
        Route::get('/stats/year', [MemberStatsController::class, 'year']);
        Route::get('/stats/month', [MemberStatsController::class, 'month']);
        Route::get('/stats/month/appointments', [MemberStatsController::class, 'monthAppointments']);
        Route::get('/points/ledger', [MemberPointLedgerController::class, 'index']);
        Route::get('/ranking/monthly', [MemberMonthlyRankingController::class, 'index']);
        Route::get('/official-account-follow', [MemberOfficialAccountFollowController::class, 'show']);
        Route::get('/notices', [MemberNoticeController::class, 'index']);
        Route::get('/notices/{notice}', [MemberNoticeController::class, 'show']);
        Route::get('/card-products', [MemberCardProductController::class, 'index']);
        Route::post('/card-purchases', [MemberCardProductController::class, 'submit']);
        Route::get('/member-cards', [MemberMemberCardController::class, 'index']);
        Route::get('/member-cards/hidden', [MemberMemberCardController::class, 'hiddenIndex']);
        Route::get('/member-cards/{memberCard}', [MemberMemberCardController::class, 'show']);
        Route::get('/member-cards/{memberCard}/ledger-entries', [MemberMemberCardController::class, 'ledgerEntries']);
        Route::get('/member-cards/{memberCard}/benefits', [MemberMemberCardController::class, 'benefits']);
        Route::post('/member-cards/{memberCard}/activate', [MemberMemberCardController::class, 'activate']);
        Route::post('/member-cards/{memberCard}/hide', [MemberMemberCardController::class, 'hide']);
        Route::post('/member-cards/{memberCard}/restore-visibility', [MemberMemberCardController::class, 'restoreVisibility']);
        Route::get('/booking/catalog', [MemberBookingCatalogController::class, 'index']);
        Route::get('/booking/private-coaches/profile', [MemberPrivateCoachController::class, 'profile']);
        Route::get('/booking/private-coaches/time-slots', [MemberPrivateCoachController::class, 'timeSlots']);
        Route::get('/booking/private-coaches/payable-cards', [MemberPrivateCoachController::class, 'payableCards']);
        Route::post('/booking/private-coaches/book', [MemberPrivateCoachController::class, 'book']);
        Route::get('/booking/sessions/{session}', [MemberBookingSessionController::class, 'show']);
        Route::get('/booking/sessions/{session}/payable-cards', [MemberBookingPayableCardController::class, 'index']);
        Route::get('/booking/appointments', [MemberAppointmentController::class, 'index']);
        Route::post('/booking/appointments', [MemberAppointmentController::class, 'store']);
        Route::post('/booking/appointments/{appointment}/cancel', [MemberAppointmentController::class, 'cancel']);
        Route::post('/booking/appointments/{appointment}/promote', [MemberAppointmentController::class, 'promote']);
    });
    Route::middleware('staff.context')->prefix('/staff')->group(function () {
        Route::get('/profile', [StaffProfileController::class, 'show']);
        Route::match(['put', 'patch'], '/profile', [StaffProfileController::class, 'update']);
        Route::post('/profile/avatar', [StaffProfileController::class, 'uploadAvatar']);
        Route::get('/constants/regions', [StaffConstantsController::class, 'regions']);
        Route::get('/constants/common-data', [StaffConstantsController::class, 'commonData']);
        Route::get('/platform/subscription/pricing', [StaffPlatformSubscriptionController::class, 'pricing']);
        Route::get('/platform/subscription/agreement', [StaffPlatformSubscriptionController::class, 'agreement']);
        Route::get('/platform/subscription/orders', [StaffPlatformSubscriptionController::class, 'orders']);
        Route::post('/platform/subscription/pay', [StaffPlatformSubscriptionController::class, 'pay']);
        Route::get('/chain/sites', [StaffChainController::class, 'sites']);
        Route::get('/chain/brand', [StaffChainController::class, 'brand']);
        Route::put('/chain/brand', [StaffChainController::class, 'updateBrand']);
        Route::get('/chain/store-courses', [StaffChainController::class, 'storeCourses']);
        Route::get('/chain/staff', [StaffChainController::class, 'staffDirectory']);
        Route::get('/chain/reports/finance/summary', [StaffChainController::class, 'financeSummary']);
        Route::get('/chain/reports/courses/summary', [StaffChainController::class, 'courseSummary']);
        Route::get('/chain/reports/members/summary', [StaffChainController::class, 'membersSummary']);
        Route::get('/roles', [StaffDirectoryController::class, 'roles']);
        Route::post('/roles', [StaffRoleController::class, 'upsert']);
        Route::get('/roles/{role}', [StaffRoleController::class, 'show']);
        Route::get('/permission-catalog', [StaffDirectoryController::class, 'permissionCatalog']);
        Route::get('/sites/{site}/staff-directory', [StaffDirectoryController::class, 'index']);
        Route::post('/sites/{site}/staff-directory', [StaffDirectoryController::class, 'store']);
        Route::get('/sites/{site}/staff-directory/{staffMember}', [StaffDirectoryController::class, 'show']);
        Route::match(['put', 'patch'], '/sites/{site}/staff-directory/{staffMember}', [StaffDirectoryController::class, 'update']);
        Route::post('/sites/{site}/staff-directory/{staffMember}/departure', [StaffDirectoryController::class, 'departure']);
        Route::post('/sites/{site}/staff-directory/{staffMember}/transfer-ownership', [StaffDirectoryController::class, 'transferOwnership']);
        Route::get('/sites/{site}/profile', [StaffSiteProfileController::class, 'show']);
        Route::match(['put', 'patch'], '/sites/{site}/profile', [StaffSiteProfileController::class, 'update']);
        Route::get('/sites/{site}/settings-hub', [StaffTenantSettingsController::class, 'hub']);
        Route::post('/sites/{site}/sharing/staff-miniapp-code', [StaffSharingController::class, 'createStaffMiniappCode']);
        Route::get('/sites/{site}/member-warm-hint', [StaffMemberExperienceController::class, 'warmHint']);
        Route::put('/sites/{site}/member-warm-hint', [StaffMemberExperienceController::class, 'updateWarmHint']);
        Route::get('/sites/{site}/member-carousel', [StaffMemberExperienceController::class, 'carousel']);
        Route::put('/sites/{site}/member-carousel', [StaffMemberExperienceController::class, 'updateCarousel']);
        Route::get('/sites/{site}/member-miniapp-layout', [StaffMemberExperienceController::class, 'miniappLayout']);
        Route::put('/sites/{site}/member-miniapp-layout', [StaffMemberExperienceController::class, 'updateMiniappLayout']);
        Route::get('/sites/{site}/member-onboarding-help', [StaffMemberExperienceController::class, 'onboardingHelp']);
        Route::put('/sites/{site}/member-onboarding-help', [StaffMemberExperienceController::class, 'updateOnboardingHelp']);
        Route::get('/sites/{site}/legal/membership-agreement', [StaffLegalConfigController::class, 'membershipAgreement']);
        Route::put('/sites/{site}/legal/membership-agreement', [StaffLegalConfigController::class, 'updateMembershipAgreement']);
        Route::get('/sites/{site}/payment-marketing', [StaffTenantSettingsController::class, 'paymentMarketing']);
        Route::get('/sites/{site}/support/contact', [StaffSupportController::class, 'contact']);
        Route::get('/sites/{site}/support/video-help', [StaffSupportController::class, 'videoHelp']);
        Route::get('/sites/{site}/notification-channels', [StaffNotificationChannelController::class, 'show']);
        Route::put('/sites/{site}/notification-channels', [StaffNotificationChannelController::class, 'update']);
        Route::get('/sites/{site}/closure-calendar', [StaffSiteClosureController::class, 'index']);
        Route::post('/sites/{site}/closure-calendar', [StaffSiteClosureController::class, 'store']);
        Route::patch('/sites/{site}/closure-calendar/{closure}', [StaffSiteClosureController::class, 'update']);
        Route::get('/sites/{site}/staff-vacations', [StaffVacationController::class, 'index']);
        Route::get('/sites/{site}/staff/{staffMember}/vacations', [StaffVacationController::class, 'staffIndex']);
        Route::post('/sites/{site}/staff/{staffMember}/vacations', [StaffVacationController::class, 'store']);
        Route::patch('/sites/{site}/staff/{staffMember}/vacations/{vacation}', [StaffVacationController::class, 'update']);
        Route::get('/sites/{site}/notices', [StaffSiteNoticeController::class, 'index']);
        Route::post('/sites/{site}/notices', [StaffSiteNoticeController::class, 'store']);
        Route::patch('/sites/{site}/notices/{notice}', [StaffSiteNoticeController::class, 'update']);
        Route::post('/sites/{site}/notices/{notice}/archive', [StaffSiteNoticeController::class, 'archive']);
        Route::get('/sites/{site}/dashboard/summary', [StaffDashboardController::class, 'summary']);
        Route::get('/sites/{site}/dashboard/sales-feed', [StaffDashboardController::class, 'salesFeed']);
        Route::get('/sites/{site}/dashboard/appointment-feed', [StaffDashboardController::class, 'appointmentFeed']);
        Route::get('/sites/{site}/crm/dashboard-summary', [StaffCrmDashboardController::class, 'summary']);
        Route::get('/sites/{site}/reports/dashboard-summary', [StaffReportDashboardController::class, 'summary']);
        Route::get('/sites/{site}/reports/finance/profit-summary', [StaffReportFinanceController::class, 'profitSummary']);
        Route::get('/sites/{site}/reports/finance/profit-calendar', [StaffReportFinanceController::class, 'profitCalendar']);
        Route::get('/sites/{site}/reports/finance/profit-daily', [StaffReportFinanceController::class, 'profitDaily']);
        Route::get('/sites/{site}/reports/courses/summary', [StaffReportCourseController::class, 'summary']);
        Route::get('/sites/{site}/reports/courses/calendar', [StaffReportCourseController::class, 'calendar']);
        Route::get('/sites/{site}/reports/courses/daily', [StaffReportCourseController::class, 'daily']);
        Route::get('/sites/{site}/reports/rankings/orders', [StaffReportRankingController::class, 'orders']);
        Route::get('/sites/{site}/reports/rankings/course-attendance', [StaffReportRankingController::class, 'courseAttendance']);
        Route::get('/sites/{site}/reports/rankings/points', [StaffReportRankingController::class, 'points']);
        Route::get('/sites/{site}/reports/rankings/sales-staff', [StaffReportRankingController::class, 'salesStaff']);
        Route::get('/sites/{site}/reports/rankings/sales-staff/{salesStaff}', [StaffReportRankingController::class, 'salesStaffDetail']);
        Route::get('/sites/{site}/reports/rankings/member-card-consumption', [StaffReportRankingController::class, 'memberCardConsumption']);
        Route::get('/sites/{site}/reports/rankings/card-product-sales', [StaffReportRankingController::class, 'cardProductSales']);
        Route::get('/sites/{site}/reports/card-product-analytics', [StaffReportRankingController::class, 'cardProductAnalytics']);
        Route::get('/sites/{site}/reports/calendar/month-options', [StaffReportCalendarController::class, 'monthOptions']);
        Route::get('/sites/{site}/reports/card-sales/summary', [StaffReportCardSalesController::class, 'summary']);
        Route::get('/sites/{site}/reports/card-sales/detail', [StaffReportCardSalesController::class, 'detail']);
        Route::get('/sites/{site}/reports/card-analyze/summary', [StaffReportCardAnalyzeController::class, 'summary']);
        Route::get('/sites/{site}/reports/change-log', [StaffReportChangeLogController::class, 'index']);
        Route::get('/sites/{site}/reports/coaches/rankings', [StaffReportCoachController::class, 'monthlyRank']);
        Route::get('/sites/{site}/reports/coaches/{coachStaff}/appointments', [StaffReportCoachController::class, 'appointmentDetail']);
        Route::get('/sites/{site}/payroll/coach-config', [StaffPayrollConfigController::class, 'coachConfig']);
        Route::put('/sites/{site}/payroll/coach-config', [StaffPayrollConfigController::class, 'updateCoachConfig']);
        Route::get('/sites/{site}/payroll/coach-rules', [StaffPayrollConfigController::class, 'coachRules']);
        Route::put('/sites/{site}/payroll/coach-rules', [StaffPayrollConfigController::class, 'updateCoachRules']);
        Route::get('/sites/{site}/payroll/sales-config', [StaffPayrollConfigController::class, 'salesConfig']);
        Route::put('/sites/{site}/payroll/sales-config', [StaffPayrollConfigController::class, 'updateSalesConfig']);
        Route::get('/sites/{site}/payroll/coaches', [StaffPayrollConfigController::class, 'coaches']);
        Route::get('/sites/{site}/payroll/coach-reports', [StaffPayrollReportController::class, 'coachReports']);
        Route::get('/sites/{site}/payroll/coach-reports/{coachStaff}', [StaffPayrollReportController::class, 'coachReportDetail']);
        Route::get('/sites/{site}/payroll/sales-reports', [StaffPayrollReportController::class, 'salesReports']);
        Route::get('/sites/{site}/payroll/sales-reports/{salesStaff}', [StaffPayrollReportController::class, 'salesReportDetail']);
        Route::get('/sites/{site}/payroll/course-commission', [StaffPayrollReportController::class, 'courseCommission']);
        Route::post('/sites/{site}/payroll/recompute-jobs', [StaffPayrollReportController::class, 'createRecomputeJob']);
        Route::get('/sites/{site}/payroll/recompute-jobs', [StaffPayrollReportController::class, 'listRecomputeJobs']);
        Route::get('/sites/{site}/reports/reminders/anniversary', [StaffNotificationReminderController::class, 'anniversary']);
        Route::get('/sites/{site}/reports/reminders/no-class', [StaffNotificationReminderController::class, 'noClass']);
        Route::get('/sites/{site}/reports/reminders/birthdays', [StaffNotificationReminderController::class, 'birthdays']);
        Route::get('/sites/{site}/reports/reminders/visitors', [StaffNotificationReminderController::class, 'visitors']);
        Route::get('/sites/{site}/reports/reminders/holiday-due', [StaffNotificationReminderController::class, 'holidayDue']);
        Route::post('/sites/{site}/exports/members', [StaffExportController::class, 'createMemberExport']);
        Route::get('/sites/{site}/exports/jobs', [StaffExportController::class, 'listJobs']);
        Route::get('/sites/{site}/exports/jobs/{job}/download', [StaffExportController::class, 'downloadJob']);
        Route::get('/sites/{site}/platform/subscription/status', [StaffPlatformSubscriptionController::class, 'siteStatus']);
        Route::get('/sites/{site}/points-config', [StaffPointsConfigController::class, 'show']);
        Route::put('/sites/{site}/points-config', [StaffPointsConfigController::class, 'update']);
        Route::post('/sites/{site}/ledger-reconciliation-jobs', [StaffLedgerReconciliationController::class, 'createJob']);
        Route::get('/sites/{site}/ledger-reconciliation-jobs', [StaffLedgerReconciliationController::class, 'listJobs']);
        Route::get('/sites/{site}/crm/member-field-policy', [StaffCrmConfigController::class, 'memberFieldPolicy']);
        Route::put('/sites/{site}/crm/member-field-policy', [StaffCrmConfigController::class, 'updateMemberFieldPolicy']);
        Route::get('/sites/{site}/crm/member-filter-presets', [StaffCrmConfigController::class, 'memberFilterPresets']);
        Route::get('/sites/{site}/crm/sales-staff', [StaffCrmConfigController::class, 'salesStaff']);
        Route::get('/sites/{site}/members', [StaffMemberController::class, 'index']);
        Route::post('/sites/{site}/members', [StaffMemberController::class, 'store']);
        Route::post('/sites/{site}/members/batch-import', [StaffMemberController::class, 'batchImport']);
        Route::get('/sites/{site}/members/booking-picker', [StaffMemberController::class, 'bookingPicker']);
        Route::get('/sites/{site}/members/deleted', [StaffMemberController::class, 'deletedIndex']);
        Route::get('/sites/{site}/members/{member}', [StaffMemberController::class, 'show']);
        Route::match(['put', 'patch'], '/sites/{site}/members/{member}', [StaffMemberController::class, 'update']);
        Route::post('/sites/{site}/members/{member}/status-transitions', [StaffMemberController::class, 'transitionStatus']);
        Route::post('/sites/{site}/members/{member}/owner-claim', [StaffMemberController::class, 'claimOwner']);
        Route::get('/sites/{site}/members/{member}/notes', [StaffMemberController::class, 'notes']);
        Route::post('/sites/{site}/members/{member}/notes', [StaffMemberController::class, 'addNote']);
        Route::put('/sites/{site}/members/{member}/tags', [StaffMemberController::class, 'syncTags']);
        Route::post('/sites/{site}/members/{member}/app-access', [StaffMemberController::class, 'changeAppAccess']);
        Route::patch('/sites/{site}/members/{member}/sticky-remark', [StaffMemberController::class, 'updateStickyRemark']);
        Route::post('/sites/{site}/members/{member}/restore', [StaffMemberController::class, 'restore']);
        Route::post('/sites/{site}/members/{member}/point-adjustments', [StaffMemberController::class, 'pointAdjust']);
        Route::get('/sites/{site}/members/{member}/point-ledger', [StaffMemberController::class, 'pointLedger']);
        Route::get('/member-tags', [MemberTagController::class, 'index']);
        Route::post('/member-tags', [MemberTagController::class, 'store']);
        Route::get('/sites/{site}/member-link-requests', [StaffMemberLinkController::class, 'index']);
        Route::post('/sites/{site}/member-link-requests/{linkRequest}/decision', [StaffMemberLinkController::class, 'decide']);
        Route::get('/sites/{site}/card-products', [StaffCardProductController::class, 'index']);
        Route::post('/sites/{site}/card-products', [StaffCardProductController::class, 'store']);
        Route::get('/sites/{site}/card-products/cross-site-links', [StaffCardProductCrossSiteController::class, 'index']);
        Route::get('/sites/{site}/card-products/face-library', [StaffCardProductController::class, 'faceLibrary']);
        Route::post('/sites/{site}/card-products/export-jobs', [StaffCardProductController::class, 'createExportJob']);
        Route::get('/sites/{site}/card-products/{cardProduct}', [StaffCardProductController::class, 'show']);
        Route::get('/sites/{site}/card-products/{cardProduct}/group-history', [StaffCardProductController::class, 'groupHistory']);
        Route::match(['put', 'patch'], '/sites/{site}/card-products/{cardProduct}', [StaffCardProductController::class, 'update']);
        Route::post('/sites/{site}/card-products/{cardProduct}/archive', [StaffCardProductController::class, 'archive']);
        Route::post('/sites/{site}/card-products/{cardProduct}/restore', [StaffCardProductController::class, 'restore']);
        Route::delete('/sites/{site}/card-products/{cardProduct}', [StaffCardProductController::class, 'destroy']);
        Route::put('/sites/{site}/card-products/{cardProduct}/cross-site-link', [StaffCardProductCrossSiteController::class, 'update']);
        Route::get('/sites/{site}/courses', [StaffCourseController::class, 'index']);
        Route::get('/sites/{site}/private-coaches', [StaffCoachPrivateProfileController::class, 'index']);
        Route::post('/sites/{site}/private-coaches', [StaffCoachPrivateProfileController::class, 'store']);
        Route::post('/sites/{site}/private-coaches/save', [StaffCoachPrivateProfileController::class, 'saveFull']);
        Route::get('/sites/{site}/private-coaches/{profile}/time-slots', [StaffCoachPrivateProfileController::class, 'timeSlots']);
        Route::post('/sites/{site}/private-coaches/{profile}/book', [StaffCoachPrivateProfileController::class, 'book']);
        Route::match(['put', 'patch'], '/sites/{site}/private-coaches/{profile}', [StaffCoachPrivateProfileController::class, 'update']);
        Route::delete('/sites/{site}/private-coaches/{profile}', [StaffCoachPrivateProfileController::class, 'destroy']);
        Route::get('/sites/{site}/course-tags', [StaffCourseController::class, 'tags']);
        Route::put('/sites/{site}/course-tags', [StaffCourseController::class, 'updateTags']);
        Route::post('/sites/{site}/courses', [StaffCourseController::class, 'store']);
        Route::get('/sites/{site}/courses/{course}', [StaffCourseController::class, 'show']);
        Route::get('/sites/{site}/courses/{course}/delete-preflight', [StaffCourseController::class, 'deletePreflight']);
        Route::match(['put', 'patch'], '/sites/{site}/courses/{course}', [StaffCourseController::class, 'update']);
        Route::post('/sites/{site}/courses/{course}/archive', [StaffCourseController::class, 'archive']);
        Route::post('/sites/{site}/courses/{course}/restore', [StaffCourseController::class, 'restore']);
        Route::delete('/sites/{site}/courses/{course}', [StaffCourseController::class, 'destroy']);
        Route::get('/sites/{site}/rooms', [StaffRoomController::class, 'index']);
        Route::post('/sites/{site}/rooms', [StaffRoomController::class, 'store']);
        Route::get('/sites/{site}/rooms/{room}', [StaffRoomController::class, 'show']);
        Route::match(['put', 'patch'], '/sites/{site}/rooms/{room}', [StaffRoomController::class, 'update']);
        Route::post('/sites/{site}/rooms/{room}/archive', [StaffRoomController::class, 'archive']);
        Route::delete('/sites/{site}/rooms/{room}', [StaffRoomController::class, 'destroy']);
        Route::get('/sites/{site}/schedule-sessions', [StaffScheduleSessionController::class, 'index']);
        Route::post('/sites/{site}/schedule-sessions', [StaffScheduleSessionController::class, 'store']);
        Route::post('/sites/{site}/schedule-sessions/batch-copy', [StaffScheduleBatchController::class, 'batchCopy']);
        Route::post('/sites/{site}/schedule-sessions/batch-suspend', [StaffScheduleBatchController::class, 'batchSuspend']);
        Route::post('/sites/{site}/schedule-sessions/batch-unsuspend', [StaffScheduleBatchController::class, 'batchUnsuspend']);
        Route::post('/sites/{site}/schedule-sessions/batch-change-course', [StaffScheduleBatchController::class, 'batchChangeCourse']);
        Route::post('/sites/{site}/schedule-sessions/batch-cancel', [StaffScheduleBatchController::class, 'batchCancel']);
        Route::get('/sites/{site}/schedule-sessions/copy-preflight', [StaffScheduleExtrasController::class, 'copyPreflight']);
        Route::get('/sites/{site}/schedule-sessions/change-course-preflight', [StaffScheduleExtrasController::class, 'changeCoursePreflight']);
        Route::get('/sites/{site}/schedule-session-colors', [StaffScheduleExtrasController::class, 'sessionColors']);
        Route::put('/sites/{site}/schedule-session-colors', [StaffScheduleExtrasController::class, 'updateSessionColors']);
        Route::get('/sites/{site}/schedule-recurring-template', [StaffScheduleExtrasController::class, 'recurringTemplate']);
        Route::post('/sites/{site}/schedule-export-image', [StaffScheduleExtrasController::class, 'exportImage']);
        Route::get('/sites/{site}/schedule-display-config', [StaffScheduleDisplayController::class, 'show']);
        Route::put('/sites/{site}/schedule-display-config', [StaffScheduleDisplayController::class, 'update']);
        Route::get('/sites/{site}/schedule-sessions/{session}', [StaffScheduleSessionController::class, 'show']);
        Route::match(['put', 'patch'], '/sites/{site}/schedule-sessions/{session}', [StaffScheduleSessionController::class, 'update']);
        Route::post('/sites/{site}/schedule-sessions/{session}/suspend', [StaffScheduleSessionController::class, 'suspend']);
        Route::post('/sites/{site}/schedule-sessions/{session}/unsuspend', [StaffScheduleSessionController::class, 'unsuspend']);
        Route::post('/sites/{site}/schedule-sessions/{session}/cancel', [StaffScheduleSessionController::class, 'cancel']);
        Route::get('/sites/{site}/booking-policy', [StaffBookingPolicyController::class, 'show']);
        Route::match(['put', 'patch'], '/sites/{site}/booking-policy', [StaffBookingPolicyController::class, 'update']);
        Route::get('/sites/{site}/booking/daily-board', [StaffBookingDailyBoardController::class, 'index']);
        Route::get('/sites/{site}/booking/upcoming', [StaffBookingHistoryController::class, 'staffUpcoming']);
        Route::get('/sites/{site}/members/{member}/booking-history', [StaffBookingHistoryController::class, 'memberHistory']);
        Route::post('/sites/{site}/schedule-sessions/{session}/share-link', [StaffBookingHistoryController::class, 'createShareLink']);
        Route::get('/sites/{site}/schedule-sessions/{session}/appointments', [StaffAppointmentController::class, 'index']);
        Route::post('/sites/{site}/schedule-sessions/{session}/appointments', [StaffAppointmentController::class, 'store']);
        Route::get('/sites/{site}/schedule-sessions/{session}/waitlist', [StaffAppointmentController::class, 'waitlist']);
        Route::post('/sites/{site}/appointments/{appointment}/cancel', [StaffAppointmentController::class, 'cancel']);
        Route::post('/sites/{site}/appointments/{appointment}/promote', [StaffAppointmentController::class, 'promote']);
        Route::post('/sites/{site}/appointments/{appointment}/mark-absent', [StaffAppointmentController::class, 'markAbsent']);
        Route::post('/sites/{site}/appointments/{appointment}/mark-check-in', [StaffCheckInController::class, 'markCheckIn']);
        Route::post('/sites/{site}/check-in/resolve', [StaffCheckInController::class, 'resolve']);
        Route::patch('/sites/{site}/appointments/{appointment}/staff-notes', [StaffAppointmentController::class, 'updateStaffNotes']);
        Route::post('/sites/{site}/appointments/{appointment}/reschedule', [StaffAppointmentController::class, 'reschedule']);
        Route::post('/sites/{site}/member-cards/batch-balance-adjustments', [StaffMemberCardBatchController::class, 'batchBalanceAdjustments']);
        Route::post('/sites/{site}/member-cards/batch-validity-extensions', [StaffMemberCardBatchController::class, 'batchValidityExtensions']);
        Route::post('/sites/{site}/member-cards/batch-freeze', [StaffMemberCardBatchController::class, 'batchFreeze']);
        Route::post('/sites/{site}/member-cards/batch-unfreeze', [StaffMemberCardBatchController::class, 'batchUnfreeze']);
        Route::get('/sites/{site}/member-cards/archived', [StaffMemberCardController::class, 'archivedIndex']);
        Route::get('/sites/{site}/member-card-reminders/expiring', [StaffMemberCardReminderController::class, 'expiring']);
        Route::get('/sites/{site}/member-card-reminders/zero-balance', [StaffMemberCardReminderController::class, 'zeroBalance']);
        Route::get('/sites/{site}/member-card-reminders/pending-open', [StaffMemberCardReminderController::class, 'pendingOpen']);
        Route::get('/sites/{site}/member-card-reminders/penalized', [StaffMemberCardReminderController::class, 'penalized']);
        Route::get('/sites/{site}/member-card-reminder-config', [StaffMemberCardReminderController::class, 'showConfig']);
        Route::put('/sites/{site}/member-card-reminder-config', [StaffMemberCardReminderController::class, 'updateConfig']);
        Route::get('/sites/{site}/members/{member}/orders', [StaffMemberCardOrderController::class, 'index']);
        Route::post('/sites/{site}/orders/{order}/amount-corrections', [StaffMemberCardOrderController::class, 'correctAmount']);
        Route::post('/sites/{site}/orders/{order}/internal-notes', [StaffMemberCardOrderController::class, 'appendInternalNote']);
        Route::post('/sites/{site}/orders/{order}/void', [StaffMemberCardOrderController::class, 'void']);
        Route::delete('/sites/{site}/orders/{order}', [StaffMemberCardOrderController::class, 'destroy']);
        Route::get('/sites/{site}/members/{member}/member-cards', [StaffMemberCardController::class, 'index']);
        Route::post('/sites/{site}/members/{member}/member-cards', [StaffMemberCardController::class, 'store']);
        Route::get('/sites/{site}/member-cards/{memberCard}', [StaffMemberCardController::class, 'show']);
        Route::get('/sites/{site}/member-cards/{memberCard}/benefits', [StaffMemberCardController::class, 'benefits']);
        Route::post('/sites/{site}/member-cards/{memberCard}/transfer-share-token', [StaffMemberCardController::class, 'transferShareToken']);
        Route::get('/sites/{site}/member-cards/{memberCard}/ledger-entries', [StaffMemberCardController::class, 'ledgerEntries']);
        Route::get('/sites/{site}/member-cards/{memberCard}/holiday-last', [StaffMemberCardController::class, 'holidayLast']);
        Route::get('/sites/{site}/member-cards/{memberCard}/freeze-ledger-last', [StaffMemberCardController::class, 'freezeLedgerLast']);
        Route::get('/sites/{site}/member-cards/{memberCard}/default-fee', [StaffMemberCardController::class, 'defaultFee']);
        Route::get('/sites/{site}/member-cards/{memberCard}/dynamic-fields', [StaffMemberCardController::class, 'dynamicFields']);
        Route::patch('/sites/{site}/member-cards/{memberCard}/opening-type', [StaffMemberCardController::class, 'updateOpeningType']);
        Route::patch('/sites/{site}/member-cards/{memberCard}/remark', [StaffMemberCardController::class, 'updateRemark']);
        Route::post('/sites/{site}/member-cards/{memberCard}/balance-adjustments', [StaffMemberCardController::class, 'balanceAdjust']);
        Route::post('/sites/{site}/member-cards/{memberCard}/count-adjustments', [StaffMemberCardController::class, 'countAdjust']);
        Route::post('/sites/{site}/member-cards/{memberCard}/freeze', [StaffMemberCardController::class, 'freeze']);
        Route::post('/sites/{site}/member-cards/{memberCard}/unfreeze', [StaffMemberCardController::class, 'unfreeze']);
        Route::post('/sites/{site}/member-cards/{memberCard}/holiday/start', [StaffMemberCardController::class, 'holidayStart']);
        Route::post('/sites/{site}/member-cards/{memberCard}/holiday/end', [StaffMemberCardController::class, 'holidayEnd']);
        Route::post('/sites/{site}/member-cards/{memberCard}/validity-extensions', [StaffMemberCardController::class, 'validityExtension']);
        Route::post('/sites/{site}/member-cards/{memberCard}/archive', [StaffMemberCardController::class, 'archive']);
        Route::post('/sites/{site}/member-cards/{memberCard}/restore', [StaffMemberCardController::class, 'restore']);
    });
});
